"""adding alias domains to excluded domains table

Revision ID: 1fe4f7af0ca6
Revises: 21fffd035b0a
Create Date: 2025-04-30 11:06:38.022664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe4f7af0ca6'
down_revision: Union[str, None] = '21fffd035b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExcludedDomains', sa.Column('alias_domains', postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExcludedDomains', 'alias_domains')
    # ### end Alembic commands ###
