"""Adding alias domains

Revision ID: 21fffd035b0a
Revises:
Create Date: 2025-04-30 10:54:36.252154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21fffd035b0a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SkippedDomains")
    op.add_column(
        "Domains",
        sa.Column("alias_domains", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Domains", "alias_domains")
    op.create_table(
        "SkippedDomains",
        sa.Column("domain_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("entity", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("domain_url", name="SkippedDomains_pkey"),
    )
    # ### end Alembic commands ###
