"""adding alias urls for entry table

Revision ID: edcc6c836097
Revises: 1fe4f7af0ca6
Create Date: 2025-04-30 12:39:40.203530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edcc6c836097'
down_revision: Union[str, None] = '1fe4f7af0ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Entries', sa.Column('alias_urls', postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Entries', 'alias_urls')
    # ### end Alembic commands ###
